"""chenges model

Revision ID: 234de3b30e67
Revises: 4e1c31e6df09
Create Date: 2021-01-22 22:18:23.229792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234de3b30e67'
down_revision = '4e1c31e6df09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
